### ISSUE TITLE
[Preset] Scarlett Johansson

### ISSUE THREAD

**Issue by bustedkiwi** [Mx772/dragons-dogma-2-auto-character-creator#23]
[info]
name = "Scarlett Johansson"
author = "https://www.reddit.com/user/HevsCreations"
source = "https://www.reddit.com/r/fashiondogma/comments/1bj6g34/scarlett_johansson/"
photo = "https://preview.redd.it/oddmj5fkhfpc1.jpeg?width=717&auto=webp&s=f7a7b76dd2fafca22b8cc834fdbd7cf1341249b5"

## Preset: 

https://pastebin.com/iXnhem4x

**Comment by Mx772** [comment]
BTW if you want, you can open pull requests for you to get code credit!

If you navigate to the folder and then click 'add file', you can basically do all the above then 'open a pull request' 

![image](https://github.com/Mx772/dragons-dogma-2-auto-character-creator/assets/9059161/daf67503-7be1-45da-8a42-1293e39d1aca)

**Comment by Mx772** [comment]
Also if you haven't tried the new config maker, takes like 2 minutes to burn through a slider preset now!

**Comment by bustedkiwi** [comment]
Oh nice, I'll give that a shot. I've been jotting these down from screenshots and videos and testing them out. Would probably be good to "backup" my own Arisen and Pawn lol

I'll try out the pull request, thanks :)

**Comment by Mx772** [comment]
Sure! 
Just for simplicity:
> You select the base/default, then can enter for each section. If you wish to skip the rest of the tool, type 'skip' in a field where it expects a number (So an attribute, not asking if you want to skip a section)

Basically for each category it asks you if you want to skip, if you click return/enter, it starts going through the categories. 
You type the number, OR if you press return/enter it keeps the default. 

If you are in a category, you can type 'skip' to complete the process (Like if you get to teeth and they have no tattoos, etc)

The latest released exe has just one issue which is that it doesn't auto-quote the 'info' sections which is an easy fix. 

Also I found a bug in the default.inis that had an extra attribute (eyelash color or something) which I deleted. So you can just pull the latest defaults if you want.

**Comment by bustedkiwi** [comment]
I tried pull requesting but it went over my head haha

Good to know about the skip, that helps with the tattoos on Bela

**Comment by Mx772** [comment]
Lol, I can try explaining a bit better
Basically go to this page:
https://github.com/Mx772/dragons-dogma-2-auto-character-creator/new/main/templates

Paste all the stuff in. 

Name the file (lowercase name).ini (scarlett_johansson.ini) 
Then click 'commit changes' (green button - top right)
Title the commit whatever you want (Generally something short like 'added scarlett_johansson.ini'
Then click 'make new branch' and name it <name> (so scarlett_johansson) 

Then it should direct you to this page:
![image](https://github.com/Mx772/dragons-dogma-2-auto-character-creator/assets/9059161/174636c9-0b2a-478a-878c-369cd011da3b)

It's 'technically' best practice to put `[main]` in the title (Because that's the 'branch' you want to merge into) 
But other than that, just click 'create pull request' 

Fun fact, if in the description of the pull request you add the keyword:
'closes' followed with the issue number, so `closes #23` in this case, it'll auto-close the issue when the pull-request merges. 
It also links the issue, so as this photo shows, you can see the pull-request from the issue...

![image](https://github.com/Mx772/dragons-dogma-2-auto-character-creator/assets/9059161/275b1c53-161d-4f56-85b0-2eb0a7e08b5c)

It'll also credit you in the release notes:
![image](https://github.com/Mx772/dragons-dogma-2-auto-character-creator/assets/9059161/6a253b3e-fdcb-4e78-85bf-64cd4de55d58)



So for `Bela Dimitrescu` for example, you could put `closes #25` and it'll close that issue when it merges!
