### ISSUE TITLE
Fem Beastren KeyError: 'bridge_bump_upper'

### ISSUE THREAD

**Issue by Kitthaven** [Mx772/dragons-dogma-2-auto-character-creator#28]
**Describe the bug**
I'm creating a female Beastren preset and when I was testing it it got to the bridge_bump_overall section and then stopped. When looking in the console it says it's trying to find bridge_bump_upper but that isn't an option for Beastren. They also don't have bridge-bump_lower.

**Version:**
v0.0.11

**To Reproduce**
Try to make a female Beastren with an edited nose I guess lol. I haven't tested if this is an issue with the male Beastren as well but it might be.

**Screenshots**
![2024-03-30 10_18_32-New Issue · Mx772_dragons-dogma-2-auto-character-creator - Opera](https://github.com/Mx772/dragons-dogma-2-auto-character-creator/assets/50052152/e9fb4dc4-30aa-4b7e-b0c6-d2ae808aa833)
![2024-03-30 10_19_01-Greenshot](https://github.com/Mx772/dragons-dogma-2-auto-character-creator/assets/50052152/2c57b883-6ea9-4050-8906-862424c1dac2)

**Desktop (please complete the following information):**
 - OS: Windows 11

Thank you!

**Comment by Mx772** [comment]
Good catch, I hadn't tested beastren after the dependency attributes update. The reason it's failing is because the 'overall' bridge attribute causes the other two sliders to change with it on humans. But in this case it's trying to change the values but can't find them because the default/preset doesn't have them. 

I can fix this a bit later!

**Comment by Kitthaven** [comment]
Ah yeah that makes sense! Thank you!
