### ISSUE TITLE
Frieren template wrong

### ISSUE THREAD

**Issue by unleashed7** [Mx772/dragons-dogma-2-auto-character-creator#29]
Not sure how the templates are added, if it gets validated or not before adding to it, but for example the hair is wrong, and other parts in it.

Supposed to be 36 not 14, like shown in the video.

![image](https://github.com/Mx772/dragons-dogma-2-auto-character-creator/assets/49449100/debd3e22-b2eb-4c31-b9b9-b582120d6cf3)

**Comment by Mx772** [comment]
They're not validated to see if they match the video/photos, no. That would basically take as much time as making the preset all over again. That being said, if one or two are off it's an easy fix to just switch the value in CC. (That's why the source is there just in case)

I don't think anyone is trolling but it takes a hot minute to make a preset and there is a _lot_ of attributes. So one or two may be incorrect. That being said I can go in and correct it for the next release or you can just change the value in CC or in the frieren preset.

**Comment by unleashed7** [comment]
Thanks, it was just surprising (disappointing?) to realise it's wrong, but I might just use to backup my own presets instead of using the templates in the end, for that's it's great!

**Comment by Mx772** [comment]
Yeah, totally understand. It looks like most of the other attributes are right though. So hoping it's just the hairstyle. 

The other thing I've ran into is some authors share sliders but don't click into categories so it doesn't show "style" attribute so it's sometimes guess work on some which is bad.
